config/routes.rb
DemoApp::Application.routes.draw do
  
  resources :projects
  
  root 'projects#index'
  match '/new',to:'projects#new',via:'get'
  match '/edit',to:'projects#edit',via: 'get'
  match '/show',to:'projects#show',via:'get' 
  match '/contact',to:'projects#contact',via:'get'

end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :name,presence: true,length: {maximum: 50}
	validates :description,presence: true
	validates :billing_type,presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def new
  	@project=Project.new
  end
  def index 
  	@project=Project.all
  end

  def create
 	@project=Project.create(project_params)
 	if @project.save
 		flash[:success]="Project Added"
 	redirect_to root_path
 	else
 		flash[:error]="Somthig goes wrong"
 			render 'new'
 	end

  end

  def show
  	@project=Project.find(params[:id])

  end
  
  def edit
  	@project=Project.find(params[:id])

  end

  def update
  	@project=Project.find(params[:id])
	@project.update_attributes(project_params)
	if @project.save
		flash[:success]="Project Added"
	redirect_to root_path
	else
		flash[:error]="Somethig goes wrong"
		redirect_to edit_project_path(params[:id])
	end

  end

  def destroy
  	Project.find(params[:id]).destroy
  	redirect_to root_path
  end
  private 
  def project_params
  	params.require(:project).permit(:name,:code,:description,:billing_type,:start_date,:dead_date,:end_date,:github_url,:status)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<small>
<a href="http://railstutorial.org/">Rails Tutorial</a>
by Hiren Bhalani
</small>
<nav>
<ul>

<li><%= link_to "Contact", contact_path %></li>

</ul>
</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<nav class="container">
			<div class="nav pull-left">
				<%= image_tag(("tracking.jpg"), :class => "logo") %>
			</div>
			<div class="nav pull-center">
			<h3>Project Tracking</h3> 
			</div>
			<div class="nav pull-right">
			<%= link_to "Home", root_path %>
			</div>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoApp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%=render 'layouts/header' %>
<div class="container">
<% flash.each do |key,value| %>
		<div class="alert alert-<%=key%>"><%= value %></div>
	<% end %>

<%= yield %>
<%=render 'layouts/footer' %>
</div>
</body>
</html>

app/views/projects/contact.html.erb
<h2> Address: </h2>
<p> 
FF – 1,2, JBR Arcade, Science City Road, Ahmedabad, Gujarat, India </p>

<h4> Email </h4>
<p> sales@botreeconsulting.com
</p>

app/views/projects/edit.html.erb
<h3> Edit project </h3>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@project) do |f| %>

		
      
			<%= f.label :name%>
			<%= f.text_field :name %>

			<%= f.label :code %>
			<%= f.text_field :code %>

			<%= f.label :description %>
			<%= f.text_field :description %>

			<%= f.label :billing_type %>
			<%= f.select :billing_type,options_for_select(%w[tnm fixed]) %>

			<%= f.label :start_date %>
			<%= f.date_field :start_date %>

			<%= f.label :deadline_date%>
			<%= f.date_field :dead_date %>

			<%= f.label :end_date %>
			<%= f.date_field :end_date %>

			<%= f.label :github_url%>
			<%= f.text_field :github_url%>
			
			<%= f.label :status %>
			<%= f.select :status,options_for_select(%w[poc kick_off completed]) %>

			
			

			<%= f.submit "Add project", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/projects/index.html.erb
<h3><%= link_to "Add new project",new_path%></h3>

<div style="padding:30px 30px 30px 0px;">

<table class="table table-striped table-bordered table-condensed">
	<tr> 
	<th>name</th>
	<th>code</th>
	<th>description</th>
	<th>billing type</th>
	<th>start date</th>
	<th>deadline</th>
	<th>end date</th>
	<th>github url</th>
	<th>status</th>
	<th>Action</th>
	</tr>
	<% @project.each do |p| %> 
	<tr>
	<td><%= link_to p.name, project_path(p) %></td>
	<td><%= p.code %></td>
	<td><%= p.description %></td>
	<td><%= p.billing_type %></td>
	<td><%= p.start_date %></td>
	<td><%= p.dead_date %></td>
	<td><%= p.end_date %></td>
	<td><%= p.github_url %></td>
	<td><%= p.status %></td>
	<td><%= link_to "Edit", edit_project_path(p) %>/<%= link_to "Delete",project_path(p),method: :delete,data:{confirm:"Are you Sure??"}%></td>
	</tr>
	<% end %>


</table>


</div>

app/views/projects/new.html.erb
<h1> New Project</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@project) do |f| %>

		
      
			<%= f.label :name%>
			<%= f.text_field :name %>

			<%= f.label :code %>
			<%= f.text_field :code %>

			<%= f.label :description %>
			<%= f.text_field :description %>

			<%= f.label :billing_type %>
			<%= f.select :billing_type,options_for_select(%w[tnm fixed]) %>

			<%= f.label :start_date %>
			<%= f.date_field :start_date %>

			<%= f.label :deadline_date%>
			<%= f.date_field :dead_date %>

			<%= f.label :end_date %>
			<%= f.date_field :end_date %>

			<%= f.label :github_url%>
			<%= f.text_field :github_url%>
			
			<%= f.label :status %>
			<%= f.select :status,options_for_select(%w[poc kick_off completed]) %>

			
			

			<%= f.submit "Add project", class: "btn btn-large btn-primary" %>
		<% end %>
	</div>
</div>

app/views/projects/show.html.erb
<div style="padding:30px 30px 30px 0px;">

<table class="table table-striped table-bordered table-condensed">
	<tr> 
	<th>name</th>
	<th>code</th>
	<th>description</th>
	<th>billing type</th>
	<th>start date</th>
	<th>deadline</th>
	<th>end date</th>
	<th>github url</th>
	<th>status</th>
	<th>Action</th>
	</tr>
	<tr>
	<td><%= @project.name %></td>
	<td><%= @project.code %></td>
	<td><%= @project.description %></td>
	<td><%= @project.billing_type %></td>
	<td><%= @project.start_date %></td>
	<td><%= @project.dead_date %></td>
	<td><%= @project.end_date %></td>
	<td><%= @project.github_url %></td>
	<td><%= @project.status %></td>
	<td><%= link_to "Edit", edit_project_path%>/<%= link_to "Delete",project_path, method: :delete, data: {confirm: "You sure?"} %> </td>
	</tr>


</table>


</div>